export const LOADING_USERS = 'LOADING_USERS';
export const LOADING_USERS_SUCCESS = 'LOADING_USERS_SUCCESS';
export const LOADING_USERS_ERROR = 'LOADING_USERS_SUCCESS';

export const userActions = {
    DELETEING_USER: 'DELETEING_USER',
    DELETEING_USER_SUCCESS: 'DELETEING_USER_SUCCESS',
    DELETEING_USER_ERROR: 'DELETEING_USER_ERROR',
    ADDING_USER: 'ADDING_USER',
    ADDING_USER_ERROR: 'ADDING_USER_ERROR',
    LOADING_SELECTED_USER: 'LOADING_SELECTED_USER',
    LOADING_SELECTED_SUCCESS: 'LOADING_SELECTED_SUCCESS',
    LOADING_SELECTED_ERROR: 'LOADING_SELECTED_ERROR',
    LOADING_ACCOUNT_TYPES: 'LOADING_ACCOUNT_TYPES',
    LOADING_ACCOUNT_SUCCESS: 'LOADING_ACCOUNT_SUCCESS',
    LOADING_ACCOUNT_ERROR: 'LOADING_ACCOUNT_ERROR',
    UPDATING_USER: 'UPDATING_USER',
    UPDATING_USER_SUCCESS: 'UPDATING_USER_SUCCESS',
    UPDATING_USER_ERROR: 'UPDATING_USER_ERROR',
    DELETEING_ACCOUNT: 'DELETEING_ACCOUNT',
    DELETEING_ACCOUNT_SUCCESS: 'DELETEING_ACCOUNT_SUCCESS',
    DELETEING_ACCOUNT_ERROR: 'DELETEING_ACCOUNT_ERROR',
    ADDING_ACCOUNT: 'ADDING_ACCOUNT',
    ADDING_ACCOUNT_SUCCESS: 'ADDING_ACCOUNT_SUCCESS',
    ADDING_ACCOUNT_ERROR: 'ADDING_ACCOUNT_ERROR'
};