export const LOADING_USERS = 'LOADING_USERS';
export const LOADING_USERS_SUCCESS = 'LOADING_USERS_SUCCESS';
export const LOADING_USERS_ERROR = 'LOADING_USERS_SUCCESS';

export const userActions = {
    DELETEING_USER: 'DELETEING_USER',
    DELETEING_USER_SUCCESS: 'DELETEING_USER_SUCCESS',
    DELETEING_USER_ERROR: 'DELETEING_USER_ERROR'
};